version: 1
accounts:
  - name: user1
    coins: ["100000000xyz"]
  - name: user2
    coins: ["1000token,100000000xyz"]
validator:
  name: user1
  staked: "100000000xyz"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "xyz"
        max_validators: "2"
